export const AudioAssets: { [key: string]: any } = {
    'Apple.mp3': require('../../assets/audio/Apple.mp3'),
    'Book.mp3': require('../../assets/audio/Book.mp3'),
    'Car.mp3': require('../../assets/audio/Car.mp3'),
    'Cat.mp3': require('../../assets/audio/Cat.mp3'),
    'Dog.mp3': require('../../assets/audio/Dog.mp3'),
    'Friend.mp3': require('../../assets/audio/Friend.mp3'),
    'Hello.mp3': require('../../assets/audio/Hello.mp3'),
    'House.mp3': require('../../assets/audio/House.mp3'),
    'Thank you.mp3': require('../../assets/audio/Thank you.mp3'),
    'Water.mp3': require('../../assets/audio/Water.mp3'),
    'Airport.mp3': require('../../assets/audio/Airport.mp3'),
    'Hotel.mp3': require('../../assets/audio/Hotel.mp3'),
    'Jacket.mp3': require('../../assets/audio/Jacket.mp3'),
    'Map.mp3': require('../../assets/audio/Map.mp3'),
    'Passport.mp3': require('../../assets/audio/Passport.mp3'),
    'Rain.mp3': require('../../assets/audio/Rain.mp3'),
    'Shoes.mp3': require('../../assets/audio/Shoes.mp3'),
    'Sunny.mp3': require('../../assets/audio/Sunny.mp3'),
    'Ticket.mp3': require('../../assets/audio/Ticket.mp3'),
    'Train.mp3': require('../../assets/audio/Train.mp3'),
    'Career.mp3': require('../../assets/audio/Career.mp3'),
    'Environment.mp3': require('../../assets/audio/Environment.mp3'),
    'Health.mp3': require('../../assets/audio/Health.mp3'),
    'Interview.mp3': require('../../assets/audio/Interview.mp3'),
    'Medicine.mp3': require('../../assets/audio/Medicine.mp3'),
    'Pollution.mp3': require('../../assets/audio/Pollution.mp3'),
    'Promotion.mp3': require('../../assets/audio/Promotion.mp3'),
    'Recycle.mp3': require('../../assets/audio/Recycle.mp3'),
    'Salary.mp3': require('../../assets/audio/Salary.mp3'),
    'Symptom.mp3': require('../../assets/audio/Symptom.mp3'),
};
